// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: geolocation.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateGeolocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *UpdateGeolocationRequest) Reset() {
	*x = UpdateGeolocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGeolocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGeolocationRequest) ProtoMessage() {}

func (x *UpdateGeolocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGeolocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateGeolocationRequest) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateGeolocationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateGeolocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateGeolocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type UpdateGeolocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateGeolocationResponse) Reset() {
	*x = UpdateGeolocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGeolocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGeolocationResponse) ProtoMessage() {}

func (x *UpdateGeolocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGeolocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateGeolocationResponse) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateGeolocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindNearbyUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resolution int64 `protobuf:"varint,2,opt,name=resolution,proto3" json:"resolution,omitempty"` //радиус поиска (индекс от 1 до 16, где 9 - 1.22км)
}

func (x *FindNearbyUsersRequest) Reset() {
	*x = FindNearbyUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNearbyUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearbyUsersRequest) ProtoMessage() {}

func (x *FindNearbyUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearbyUsersRequest.ProtoReflect.Descriptor instead.
func (*FindNearbyUsersRequest) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{2}
}

func (x *FindNearbyUsersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FindNearbyUsersRequest) GetResolution() int64 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

type NearbyUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance float64 `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
}

func (x *NearbyUser) Reset() {
	*x = NearbyUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyUser) ProtoMessage() {}

func (x *NearbyUser) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyUser.ProtoReflect.Descriptor instead.
func (*NearbyUser) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{3}
}

func (x *NearbyUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NearbyUser) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type FindNearbyUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*NearbyUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *FindNearbyUsersResponse) Reset() {
	*x = FindNearbyUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNearbyUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearbyUsersResponse) ProtoMessage() {}

func (x *FindNearbyUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearbyUsersResponse.ProtoReflect.Descriptor instead.
func (*FindNearbyUsersResponse) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{4}
}

func (x *FindNearbyUsersResponse) GetUsers() []*NearbyUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idresp   int64 `protobuf:"varint,1,opt,name=idresp,proto3" json:"idresp,omitempty"`
	IdTarget int64 `protobuf:"varint,2,opt,name=idTarget,proto3" json:"idTarget,omitempty"`
}

func (x *GetUserLocationRequest) Reset() {
	*x = GetUserLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLocationRequest) ProtoMessage() {}

func (x *GetUserLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLocationRequest.ProtoReflect.Descriptor instead.
func (*GetUserLocationRequest) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserLocationRequest) GetIdresp() int64 {
	if x != nil {
		return x.Idresp
	}
	return 0
}

func (x *GetUserLocationRequest) GetIdTarget() int64 {
	if x != nil {
		return x.IdTarget
	}
	return 0
}

type UserLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *UserLocation) Reset() {
	*x = UserLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocation) ProtoMessage() {}

func (x *UserLocation) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocation.ProtoReflect.Descriptor instead.
func (*UserLocation) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{6}
}

func (x *UserLocation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UserLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetUserLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *UserLocation `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GetUserLocationResponse) Reset() {
	*x = GetUserLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLocationResponse) ProtoMessage() {}

func (x *GetUserLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLocationResponse.ProtoReflect.Descriptor instead.
func (*GetUserLocationResponse) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserLocationResponse) GetLocation() *UserLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type ShareLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idresp   int64                `protobuf:"varint,1,opt,name=idresp,proto3" json:"idresp,omitempty"`
	IdTarget int64                `protobuf:"varint,2,opt,name=idTarget,proto3" json:"idTarget,omitempty"`
	TimeEnd  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
}

func (x *ShareLocationRequest) Reset() {
	*x = ShareLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareLocationRequest) ProtoMessage() {}

func (x *ShareLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareLocationRequest.ProtoReflect.Descriptor instead.
func (*ShareLocationRequest) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{8}
}

func (x *ShareLocationRequest) GetIdresp() int64 {
	if x != nil {
		return x.Idresp
	}
	return 0
}

func (x *ShareLocationRequest) GetIdTarget() int64 {
	if x != nil {
		return x.IdTarget
	}
	return 0
}

func (x *ShareLocationRequest) GetTimeEnd() *timestamp.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

type ShareLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ShareLocationResponse) Reset() {
	*x = ShareLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareLocationResponse) ProtoMessage() {}

func (x *ShareLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareLocationResponse.ProtoReflect.Descriptor instead.
func (*ShareLocationResponse) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{9}
}

func (x *ShareLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopSharingLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReceiverId int64 `protobuf:"varint,2,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
}

func (x *StopSharingLocationRequest) Reset() {
	*x = StopSharingLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSharingLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSharingLocationRequest) ProtoMessage() {}

func (x *StopSharingLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSharingLocationRequest.ProtoReflect.Descriptor instead.
func (*StopSharingLocationRequest) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{10}
}

func (x *StopSharingLocationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StopSharingLocationRequest) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

type StopSharingLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StopSharingLocationResponse) Reset() {
	*x = StopSharingLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSharingLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSharingLocationResponse) ProtoMessage() {}

func (x *StopSharingLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSharingLocationResponse.ProtoReflect.Descriptor instead.
func (*StopSharingLocationResponse) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{11}
}

func (x *StopSharingLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetLocationPrivacyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Visibility string `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
}

func (x *SetLocationPrivacyRequest) Reset() {
	*x = SetLocationPrivacyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLocationPrivacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationPrivacyRequest) ProtoMessage() {}

func (x *SetLocationPrivacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationPrivacyRequest.ProtoReflect.Descriptor instead.
func (*SetLocationPrivacyRequest) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{12}
}

func (x *SetLocationPrivacyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetLocationPrivacyRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type SetLocationPrivacyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SetLocationPrivacyResponse) Reset() {
	*x = SetLocationPrivacyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLocationPrivacyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationPrivacyResponse) ProtoMessage() {}

func (x *SetLocationPrivacyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationPrivacyResponse.ProtoReflect.Descriptor instead.
func (*SetLocationPrivacyResponse) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{13}
}

func (x *SetLocationPrivacyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LocationHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Latitude  float64              `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64              `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *LocationHistory) Reset() {
	*x = LocationHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationHistory) ProtoMessage() {}

func (x *LocationHistory) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationHistory.ProtoReflect.Descriptor instead.
func (*LocationHistory) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{14}
}

func (x *LocationHistory) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LocationHistory) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationHistory) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetLocationHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetLocationHistoryRequest) Reset() {
	*x = GetLocationHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationHistoryRequest) ProtoMessage() {}

func (x *GetLocationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetLocationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{15}
}

func (x *GetLocationHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLocationHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History []*LocationHistory `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
}

func (x *GetLocationHistoryResponse) Reset() {
	*x = GetLocationHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationHistoryResponse) ProtoMessage() {}

func (x *GetLocationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetLocationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{16}
}

func (x *GetLocationHistoryResponse) GetHistory() []*LocationHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type ClearLocationHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ClearLocationHistoryRequest) Reset() {
	*x = ClearLocationHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearLocationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLocationHistoryRequest) ProtoMessage() {}

func (x *ClearLocationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLocationHistoryRequest.ProtoReflect.Descriptor instead.
func (*ClearLocationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{17}
}

func (x *ClearLocationHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ClearLocationHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClearLocationHistoryResponse) Reset() {
	*x = ClearLocationHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearLocationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLocationHistoryResponse) ProtoMessage() {}

func (x *ClearLocationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLocationHistoryResponse.ProtoReflect.Descriptor instead.
func (*ClearLocationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_geolocation_proto_rawDescGZIP(), []int{18}
}

func (x *ClearLocationHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_geolocation_proto protoreflect.FileDescriptor

var file_geolocation_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6d, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x22, 0x35, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x51, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x4e,
	0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x38, 0x0a, 0x0a, 0x4e, 0x65,
	0x61, 0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x22, 0x48, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x65, 0x61, 0x72,
	0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2d, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x61,
	0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x4c,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x72, 0x65,
	0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x72, 0x65, 0x73, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x69, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x58, 0x0a, 0x0c,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x50, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x80, 0x01, 0x0a, 0x14, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x69, 0x64, 0x72, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x64, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x55,
	0x0a, 0x1a, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x1b, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x68, 0x61,
	0x72, 0x69, 0x6e, 0x67, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x54,
	0x0a, 0x19, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x22, 0x36, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x85, 0x01, 0x0a,
	0x0f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x22, 0x34, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x65, 0x6f, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x22, 0x36, 0x0a, 0x1b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x1c, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0xb1, 0x06, 0x0a, 0x12, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25,
	0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a,
	0x0f, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x23, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x67, 0x65, 0x6f,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x68, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x68, 0x61, 0x72, 0x69,
	0x6e, 0x67, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x6f, 0x70, 0x53, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x12, 0x53,
	0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63,
	0x79, 0x12, 0x26, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x65, 0x6f, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x65, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x26, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x14, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x28, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67, 0x65,
	0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geolocation_proto_rawDescOnce sync.Once
	file_geolocation_proto_rawDescData = file_geolocation_proto_rawDesc
)

func file_geolocation_proto_rawDescGZIP() []byte {
	file_geolocation_proto_rawDescOnce.Do(func() {
		file_geolocation_proto_rawDescData = protoimpl.X.CompressGZIP(file_geolocation_proto_rawDescData)
	})
	return file_geolocation_proto_rawDescData
}

var file_geolocation_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_geolocation_proto_goTypes = []any{
	(*UpdateGeolocationRequest)(nil),     // 0: geolocation.UpdateGeolocationRequest
	(*UpdateGeolocationResponse)(nil),    // 1: geolocation.UpdateGeolocationResponse
	(*FindNearbyUsersRequest)(nil),       // 2: geolocation.FindNearbyUsersRequest
	(*NearbyUser)(nil),                   // 3: geolocation.NearbyUser
	(*FindNearbyUsersResponse)(nil),      // 4: geolocation.FindNearbyUsersResponse
	(*GetUserLocationRequest)(nil),       // 5: geolocation.GetUserLocationRequest
	(*UserLocation)(nil),                 // 6: geolocation.UserLocation
	(*GetUserLocationResponse)(nil),      // 7: geolocation.GetUserLocationResponse
	(*ShareLocationRequest)(nil),         // 8: geolocation.ShareLocationRequest
	(*ShareLocationResponse)(nil),        // 9: geolocation.ShareLocationResponse
	(*StopSharingLocationRequest)(nil),   // 10: geolocation.StopSharingLocationRequest
	(*StopSharingLocationResponse)(nil),  // 11: geolocation.StopSharingLocationResponse
	(*SetLocationPrivacyRequest)(nil),    // 12: geolocation.SetLocationPrivacyRequest
	(*SetLocationPrivacyResponse)(nil),   // 13: geolocation.SetLocationPrivacyResponse
	(*LocationHistory)(nil),              // 14: geolocation.LocationHistory
	(*GetLocationHistoryRequest)(nil),    // 15: geolocation.GetLocationHistoryRequest
	(*GetLocationHistoryResponse)(nil),   // 16: geolocation.GetLocationHistoryResponse
	(*ClearLocationHistoryRequest)(nil),  // 17: geolocation.ClearLocationHistoryRequest
	(*ClearLocationHistoryResponse)(nil), // 18: geolocation.ClearLocationHistoryResponse
	(*timestamp.Timestamp)(nil),          // 19: google.protobuf.Timestamp
}
var file_geolocation_proto_depIdxs = []int32{
	3,  // 0: geolocation.FindNearbyUsersResponse.users:type_name -> geolocation.NearbyUser
	6,  // 1: geolocation.GetUserLocationResponse.location:type_name -> geolocation.UserLocation
	19, // 2: geolocation.ShareLocationRequest.timeEnd:type_name -> google.protobuf.Timestamp
	19, // 3: geolocation.LocationHistory.timestamp:type_name -> google.protobuf.Timestamp
	14, // 4: geolocation.GetLocationHistoryResponse.history:type_name -> geolocation.LocationHistory
	0,  // 5: geolocation.GeolocationService.UpdateGeolocation:input_type -> geolocation.UpdateGeolocationRequest
	2,  // 6: geolocation.GeolocationService.FindNearbyUsers:input_type -> geolocation.FindNearbyUsersRequest
	5,  // 7: geolocation.GeolocationService.GetUserLocation:input_type -> geolocation.GetUserLocationRequest
	8,  // 8: geolocation.GeolocationService.ShareLocation:input_type -> geolocation.ShareLocationRequest
	10, // 9: geolocation.GeolocationService.StopSharingLocation:input_type -> geolocation.StopSharingLocationRequest
	12, // 10: geolocation.GeolocationService.SetLocationPrivacy:input_type -> geolocation.SetLocationPrivacyRequest
	15, // 11: geolocation.GeolocationService.GetLocationHistory:input_type -> geolocation.GetLocationHistoryRequest
	17, // 12: geolocation.GeolocationService.ClearLocationHistory:input_type -> geolocation.ClearLocationHistoryRequest
	1,  // 13: geolocation.GeolocationService.UpdateGeolocation:output_type -> geolocation.UpdateGeolocationResponse
	4,  // 14: geolocation.GeolocationService.FindNearbyUsers:output_type -> geolocation.FindNearbyUsersResponse
	7,  // 15: geolocation.GeolocationService.GetUserLocation:output_type -> geolocation.GetUserLocationResponse
	9,  // 16: geolocation.GeolocationService.ShareLocation:output_type -> geolocation.ShareLocationResponse
	11, // 17: geolocation.GeolocationService.StopSharingLocation:output_type -> geolocation.StopSharingLocationResponse
	13, // 18: geolocation.GeolocationService.SetLocationPrivacy:output_type -> geolocation.SetLocationPrivacyResponse
	16, // 19: geolocation.GeolocationService.GetLocationHistory:output_type -> geolocation.GetLocationHistoryResponse
	18, // 20: geolocation.GeolocationService.ClearLocationHistory:output_type -> geolocation.ClearLocationHistoryResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_geolocation_proto_init() }
func file_geolocation_proto_init() {
	if File_geolocation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_geolocation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGeolocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGeolocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FindNearbyUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*NearbyUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FindNearbyUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UserLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ShareLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ShareLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*StopSharingLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*StopSharingLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SetLocationPrivacyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SetLocationPrivacyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*LocationHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetLocationHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetLocationHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ClearLocationHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*ClearLocationHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geolocation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geolocation_proto_goTypes,
		DependencyIndexes: file_geolocation_proto_depIdxs,
		MessageInfos:      file_geolocation_proto_msgTypes,
	}.Build()
	File_geolocation_proto = out.File
	file_geolocation_proto_rawDesc = nil
	file_geolocation_proto_goTypes = nil
	file_geolocation_proto_depIdxs = nil
}
