
services:
  db:
    image: postgres:16.3
    container_name: ${CONTAINER_PREFIX}-db
    hostname: ${DB_HOST}-db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d users_db" ]
      interval: 2s
      timeout: 2s
      retries: 2
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - users-net

  elasticsearch:
    image: elasticsearch:8.0.0
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '9200:9200'
    environment:
      - ELASTIC_PASSWORD=pass
    
    networks:
      - elasticsearch
      
 
networks:
  users-net:
    driver: bridge
  elasticsearch:
    name: elastic
    driver: bridge